import { AppError } from '../lib/app-error.js'

export const providerErrors = {
  profileNotFound: () => new AppError(404, 'Provider profile not found', 'PROVIDER_PROFILE_NOT_FOUND'),
  updateProfileFailed: () => new AppError(500, 'Failed to update profile', 'PROVIDER_UPDATE_PROFILE_FAILED'),
  invalidSubcategoryIds: () => new AppError(400, 'Invalid subcategory IDs', 'PROVIDER_INVALID_SUBCATEGORY_IDS'),
  tooManyMainCategories: () => new AppError(400, 'Subcategories must belong to at most 5 main categories', 'PROVIDER_TOO_MANY_MAIN_CATEGORIES'),
  tooManySubcategories: () => new AppError(400, 'Cannot have more than 10 subcategories', 'PROVIDER_TOO_MANY_SUBCATEGORIES'),
  updateCategoriesFailed: () => new AppError(500, 'Failed to update categories', 'PROVIDER_UPDATE_CATEGORIES_FAILED'),
  fetchCategoriesFailed: () => new AppError(500, 'Failed to fetch categories', 'PROVIDER_FETCH_CATEGORIES_FAILED'),
  fetchWorkPostsFailed: () => new AppError(500, 'Failed to fetch work posts', 'PROVIDER_FETCH_WORK_POSTS_FAILED'),
  workPostNotFound: () => new AppError(404, 'Work post not found', 'PROVIDER_WORK_POST_NOT_FOUND'),
  subcategoryNotRegistered: () => new AppError(400, 'Subcategory must be one of your registered categories', 'PROVIDER_SUBCATEGORY_NOT_REGISTERED'),
  createWorkPostFailed: () => new AppError(500, 'Failed to create work post', 'PROVIDER_CREATE_WORK_POST_FAILED'),
  notAuthorized: () => new AppError(403, 'Not authorized', 'PROVIDER_FORBIDDEN'),
  updateWorkPostFailed: () => new AppError(500, 'Failed to update work post', 'PROVIDER_UPDATE_WORK_POST_FAILED'),
  deleteWorkPostFailed: () => new AppError(500, 'Failed to delete work post', 'PROVIDER_DELETE_WORK_POST_FAILED'),
  generateUploadUrlFailed: () => new AppError(500, 'Failed to generate upload URL', 'PROVIDER_GENERATE_UPLOAD_URL_FAILED'),
  certificationNotFound: () => new AppError(404, 'Certification not found', 'PROVIDER_CERTIFICATION_NOT_FOUND'),
  fetchCertificationsFailed: () => new AppError(500, 'Failed to fetch certifications', 'PROVIDER_FETCH_CERTIFICATIONS_FAILED'),
  createCertificationFailed: () => new AppError(500, 'Failed to create certification', 'PROVIDER_CREATE_CERTIFICATION_FAILED'),
  updateCertificationFailed: () => new AppError(500, 'Failed to update certification', 'PROVIDER_UPDATE_CERTIFICATION_FAILED'),
  deleteCertificationFailed: () => new AppError(500, 'Failed to delete certification', 'PROVIDER_DELETE_CERTIFICATION_FAILED'),
  fetchPublicProfileFailed: () => new AppError(500, 'Failed to fetch provider profile', 'PROVIDER_FETCH_PUBLIC_PROFILE_FAILED'),
  fetchReviewsFailed: () => new AppError(500, 'Failed to fetch reviews', 'PROVIDER_FETCH_REVIEWS_FAILED'),
}
